from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager

from backend.app.config import get_settings

try:
    import psycopg2
    import psycopg2.extras
except Exception:  # pragma: no cover - optional dependency in local dev
    psycopg2 = None


def get_db_path() -> str:
    settings = get_settings()
    return settings.sqlite_path


def _get_database_url() -> str | None:
    return (
        os.getenv("DATABASE_URL")
        or os.getenv("ANIME_DATABASE_URL")
        or os.getenv("ANIME_POSTGRES_URL")
        or os.getenv("ANIME_PRISMA_DATABASE_URL")
    )


def _use_postgres() -> bool:
    return bool(_get_database_url())


def using_postgres() -> bool:
    return _use_postgres()


class _CursorWrapper:
    def __init__(self, cursor, use_postgres: bool):
        self._cursor = cursor
        self._use_postgres = use_postgres

    def _translate(self, query: str) -> str:
        if not self._use_postgres:
            return query
        # Convert sqlite-style placeholders to psycopg2.
        return query.replace("?", "%s")

    def execute(self, query, params=None):
        self._cursor.execute(self._translate(query), params or ())
        return self

    def executemany(self, query, param_seq):
        self._cursor.executemany(self._translate(query), param_seq)
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __getattr__(self, name):
        return getattr(self._cursor, name)


def init_db() -> None:
    if _use_postgres():
        if psycopg2 is None:
            raise RuntimeError("psycopg2 is required for PostgreSQL support")
        conn = psycopg2.connect(_get_database_url())
        try:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS users (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username TEXT NOT NULL UNIQUE,
                        password_hash TEXT NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS favorites (
                        user_id INTEGER NOT NULL,
                        anime_id INTEGER NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        PRIMARY KEY (user_id, anime_id),
                        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                    )
                    """
                )
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS anime_summaries (
                        title_norm TEXT PRIMARY KEY,
                        title TEXT NOT NULL,
                        anime_id INTEGER,
                        summary TEXT NOT NULL,
                        source TEXT NOT NULL,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            conn.commit()
        finally:
            conn.close()
        return

    with sqlite3.connect(get_db_path()) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS favorites (
                user_id INTEGER NOT NULL,
                anime_id INTEGER NOT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (user_id, anime_id),
                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS anime_summaries (
                title_norm TEXT PRIMARY KEY,
                title TEXT NOT NULL,
                anime_id INTEGER,
                summary TEXT NOT NULL,
                source TEXT NOT NULL,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.commit()


@contextmanager
def db_cursor():
    if _use_postgres():
        if psycopg2 is None:
            raise RuntimeError("psycopg2 is required for PostgreSQL support")
        conn = psycopg2.connect(_get_database_url())
        try:
            cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
            yield conn, _CursorWrapper(cur, use_postgres=True)
            conn.commit()
        finally:
            conn.close()
        return

    conn = sqlite3.connect(get_db_path())
    conn.row_factory = sqlite3.Row
    try:
        yield conn, _CursorWrapper(conn.cursor(), use_postgres=False)
        conn.commit()
    finally:
        conn.close()
